[input]
filename = "/path/to/dataset.tif"
angles = "/path/to/angles.txt"

[output]
filename = "output.tiff"

[recon_params]
max_iters = 50
inner_iters = 5
tol = 1e-5
xtol = 1e-5
thickness = 21

[recon_params.optimizer]
method = "split_bregman"

[recon_params.optimizer.split_bregman]
lambda = 0.1
mu = 5.0
