[input]
filename = "/home/dkumar/data/shapiro/stxm/transposed.tif"
angles = "/home/dkumar/data/shapiro/stxm/angles.txt"

[output]
filename = "dino_stxm_sb.tiff"

[recon_params]
max_iters = 50
tol = 1e-5
xtol = 1e-5
thickness = 64

[recon_params.optimizer]
method = "split_bregman"

[recon_params.optimizer.split_bregman]
lambda = 0.01
mu = 10

