[input]
data_path = "/home/dkumar/data/shapiro/MCD/SimulatedData/Phantom"
component_1 = "XMCD_phantom_component1.tiff"
component_2 = "XMCD_phantom_component2.tiff"
component_3 = "XMCD_phantom_component3.tiff"

[angles]
min = -60
max = 60
steps = 121


[orientation]
gamma = 45

[output]
output = "projection.tiff"
